mu=[1;2;3];% input mean vector
sigma=[1,-0.8,0.1;-0.8,2,-0.5;0.1,-0.5,3]; %input covariance matrix
random=mvnrnd(mu,sigma,1000); %random coordinates generated by insular mvn random generator
plot3(random(:,1),random(:,2),random(:,3),"rx") %plot random dots.